# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0066_auto_20171017_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='change_of_scope',
        ),
        migrations.AddField(
            model_name='weeklyreportcomments',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreportcomments',
            name='type',
            field=models.CharField(choices=[('CS', 'Change of scope'), ('CU', 'Custom page'), ('S', 'Summary'), ('A', 'Approval')], default='A', max_length=2),
        ),
    ]
