# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0067_auto_20171018_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreportcomments',
            name='type',
            field=models.CharField(choices=[('CS', 'Change of scope'), ('CU', 'Custom page'), ('S', 'Summary'), ('A', 'Approval'), ('NW', 'Next week')], default='A', max_length=2),
        ),
    ]
